### ISSUE TITLE
Padding is at most two =s, not three

### ISSUE THREAD

**Issue by coolaj86** [RGBboy/urlsafe-base64#10]
According to https://en.wikipedia.org/wiki/Base64 and the implementation of `window.atob`, the padding can be 0, 1, or 2 equals (=), but not 3.

The only place I've found it explained is here:

https://gist.github.com/catwell/3046205

It seems that the `x % 4` is for the number of source bytes (i.e. binary), not the number of output characters (i.e. base64).

Anyway, having `===` breaks `window.atob` and using the method at the link above seems to work.

Would you like a PR?

**Comment by RGBboy** [comment]
I think you may be mistaken with respect to what this library implements. The `decode` function is performing the `x % 4` on an input base64 string. I believe it does the correct thing. If not I will happily accept and merge a change with supporting tests.
