### ISSUE TITLE
Difference between this and https://github.com/joaquimserafim/base64-url?

### ISSUE THREAD

**Issue by bradvogel** [RGBboy/urlsafe-base64#3]
Just curious what the difference is between this and https://github.com/joaquimserafim/base64-url? I'm currently using base64-url but want to know if you found and fixed any bugs in it - then I should be using yours instead! Thanks.

**Comment by RGBboy** [comment]
The API's are different. This one just has encode, decode and only deals directly with buffers.

This also has a validate method so you can check if a string is safe to put in or read from a URL.
