### ISSUE TITLE
RFC 6920 Support?

### ISSUE THREAD

**Issue by kabirbaidhya** [RGBboy/urlsafe-base64#8]
I just have a quick question. Does this package support conversion from/to **Unpadded 'base64url' for "named information" URI's (RFC 6920)** as listed [here](https://en.wikipedia.org/wiki/Base64#Variants_summary_table)?

**Comment by tellnes** [comment]
Yes it encodes without the `=` padding character and decodes back again without them if that is what you are asking for?

**Comment by kabirbaidhya** [comment]
Okay, thanks :+1:
